version: "2"

linters:
  enable:
    - staticcheck
    - govet
    - gocyclo
    - unused
    - revive
    - misspell
    - nolintlint
    - errcheck
    - ineffassign
  exclusions:
    paths:
      - test/includes
      - internal/parser/parser.go
    presets:
      - std-error-handling
  settings:
    gocyclo:
      min-complexity: 30
    revive:
      rules:
        - name: dot-imports
          disabled: true
    exhaustive:
      default-signifies-exhaustive: true
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: true

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

run:
  timeout: 10m
